name: CD

on:
  push:
    branches:
      - main

jobs:
    deliver:
        runs-on: ubuntu-latest

        steps:
            - name: check ou repository code
              uses: actions/checkout@v4

            - name: Simulando CD
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: |
                   HelloWorldDevOps.html
                   README.md

            